In [3]:
import pandas as pd

df=pd.read_csv('model_log.csv')
df.head()

         date    model  accuracy  loss
0  2026-09-20  Model-A      0.85  0.32
1  2026-09-21  Model-A      0.89  0.25
2  2026-09-22  Model-A      0.92  0.18

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      3 non-null      str
 1   model     3 non-null      str
 2   accuracy  3 non-null      float64
 3   loss      3 non-null      float64
dtypes: float64(2), str(2)
memory usage: 228.0 bytes

In [5]:
df.describe()

       accuracy   loss
count  3.000000  3.000
mean   0.886667  0.250
std    0.035119  0.070
min    0.850000  0.180
25%    0.870000  0.215
50%    0.890000  0.250
75%    0.905000  0.285
max    0.920000  0.320

In [7]:
df.dtypes

date            str
model           str
accuracy    float64
loss        float64
dtype: object

In [12]:
mask=df['accuracy']>0.70

In [9]:
mask

0    False
1    False
2    False
Name: accuracy, dtype: bool

In [10]:
filters=df[mask]

In [13]:
filters

Empty DataFrame
Columns: [date, model, accuracy, loss]
Index: []

In [15]:
filters.to_csv('filter.csv', index=False);
print("done")

done

In [16]:
#### exporting to excel

In [18]:
pip install openpyxl -q

SyntaxError: invalid syntax (2680419327.py, line 1)

In [19]:
%pip install openpyxl -q

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
df.to_excel('data.xlsx', index=false)

NameError: name 'false' is not defined

In [21]:
python.exe -m pip install --upgrade pip

SyntaxError: invalid syntax (3518040459.py, line 1)

In [22]:
df.to_excel('data.xlsx', index=false)

NameError: name 'false' is not defined

In [23]:

df.to_excel('data.xlsx', index=False)

In [24]:
df.to_json('data.json', index=False)

In [26]:
df.to_json('chat_data.json', orient='records', lines=True)

In [27]:
df

         date    model  accuracy  loss
0  2026-09-20  Model-A      0.85  0.32
1  2026-09-21  Model-A      0.89  0.25
2  2026-09-22  Model-A      0.92  0.18

In [28]:
df.to_excel('data.xlsx', index=False)
df

         date    model  accuracy  loss
0  2026-09-20  Model-A      0.85  0.32
1  2026-09-21  Model-A      0.89  0.25
2  2026-09-22  Model-A      0.92  0.18

In [29]:
import sqlite3

In [31]:
conn=sqlite3.connect('chat_data.db')

In [1]:
df

NameError: name 'df' is not defined

In [2]:
df=pd.read_csv('model_log.csv')

NameError: name 'pd' is not defined

In [3]:
import pandas as pd

df=pd.read_csv('model_log.csv')

In [5]:

df

         date    model  accuracy  loss
0  2026-09-20  Model-A      0.85  0.32
1  2026-09-21  Model-A      0.89  0.25
2  2026-09-22  Model-A      0.92  0.18

In [9]:
sorteddf=df.soft_values(by=['loss'], ascending=False)

AttributeError: 'DataFrame' object has no attribute 'soft_values'

In [10]:
df=pd.DataFrame(df)

In [11]:
df

         date    model  accuracy  loss
0  2026-09-20  Model-A      0.85  0.32
1  2026-09-21  Model-A      0.89  0.25
2  2026-09-22  Model-A      0.92  0.18

In [12]:
sorteddf=df.soft_values(by=['loss'], ascending=False)

AttributeError: 'DataFrame' object has no attribute 'soft_values'

In [14]:
sorteddf=df.sort_values(by=['loss'])

In [15]:
sorteddf

         date    model  accuracy  loss
2  2026-09-22  Model-A      0.92  0.18
1  2026-09-21  Model-A      0.89  0.25
0  2026-09-20  Model-A      0.85  0.32

In [16]:
sorteddf=df.sort_index()

In [17]:
sorteddf

         date    model  accuracy  loss
0  2026-09-20  Model-A      0.85  0.32
1  2026-09-21  Model-A      0.89  0.25
2  2026-09-22  Model-A      0.92  0.18

In [18]:
sorteddf=df.sort_values(by='loss', ascending=False).reset_index(drop=True)

In [19]:
sorteddf['Rank']=sorteddf.index+1
sorteddf

         date    model  accuracy  loss  Rank
0  2026-09-20  Model-A      0.85  0.32     1
1  2026-09-21  Model-A      0.89  0.25     2
2  2026-09-22  Model-A      0.92  0.18     3