In [1]:
#Introduction to pandas

import pandas as pd

data=[10,20,30,40]

series=pd.Series(data)

series

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
series=pd.Series(data, index=['a','b','c','d'])
series

a    10
b    20
c    30
d    40
dtype: int64

In [3]:
data={
    'Name':['Alice', 'Bob','ccc'],
    'Age':[23,23,45],
    'City': ['aa','bb','cc']

}
df=pd.DataFrame(data)

In [4]:
df

    Name  Age City
0  Alice   23   aa
1    Bob   23   bb
2    ccc   45   cc

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [6]:
df.describe()

             Age
count   3.000000
mean   30.333333
std    12.701706
min    23.000000
25%    23.000000
50%    23.000000
75%    34.000000
max    45.000000

In [7]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [8]:
df['Age']=df['Age'].astypes('float32')
df.dftypes

AttributeError: 'Series' object has no attribute 'astypes'

In [9]:
df['Age']=df['Age'].astype('float32')
df.dtypes

AttributeError: 'Series' object has no attribute 'astypes'

In [10]:
df['Age']=df['Age'].astype('float32')
df.dtypes

Name        str
Age     float32
City        str
dtype: object

In [11]:
df['city']=['111','222','333']

In [12]:
df

    Name   Age City city
0  Alice  23.0   aa  111
1    Bob  23.0   bb  222
2    ccc  45.0   cc  333

In [13]:
df['AgeGroup']=['young' if age < 30 else 'meture' for age in df['Age']]

In [14]:
df

    Name   Age City city AgeGroup
0  Alice  23.0   aa  111    young
1    Bob  23.0   bb  222    young
2    ccc  45.0   cc  333   meture

In [15]:
df= df.drop('AgeGroup', axis=1)

In [16]:
df

    Name   Age City city
0  Alice  23.0   aa  111
1    Bob  23.0   bb  222
2    ccc  45.0   cc  333

In [17]:
df= df.drop('city')

KeyError: "['city'] not found in axis"

In [18]:
df

    Name   Age City city
0  Alice  23.0   aa  111
1    Bob  23.0   bb  222
2    ccc  45.0   cc  333

In [19]:
df= df.drop('city', axis=1)

In [20]:
df

    Name   Age City
0  Alice  23.0   aa
1    Bob  23.0   bb
2    ccc  45.0   cc

In [21]:
df=df.drop(1)

In [22]:
df

    Name   Age City
0  Alice  23.0   aa
2    ccc  45.0   cc

In [23]:
df_copy=df.copy()

In [24]:
df_copy

    Name   Age City
0  Alice  23.0   aa
2    ccc  45.0   cc

In [26]:
df=df.assign(Discount=[5,10], Total_spend=[100,200])
df

    Name   Age City  Discount  Total_spend
0  Alice  23.0   aa         5          100
2    ccc  45.0   cc        10          200

In [27]:
data={
    'Name':['Alice', 'Bob','ccc'],
    'Age':[23,23,45],
    'City': ['aa','bb','cc']

}
df=pd.DataFrame(data)

In [28]:
df

    Name  Age City
0  Alice   23   aa
1    Bob   23   bb
2    ccc   45   cc

In [30]:
row=df.loc[2]

In [31]:
row

Name    ccc
Age      45
City     cc
Name: 2, dtype: object

In [33]:
cell=df.loc[2, 'City']

In [34]:
cell

'cc'

In [35]:
sunset=df.loc[0:1]

In [36]:
sunset

    Name  Age City
0  Alice   23   aa
1    Bob   23   bb

In [37]:
sunset=df.loc[0:1,['Name','City']]

In [38]:
sunset

    Name City
0  Alice   aa
1    Bob   bb

In [41]:
mask=df['Age']>10
fitered=df.loc[mask].iloc[:,0]
fitered

0    Alice
1      Bob
2      ccc
Name: Name, dtype: str

In [43]:
df.iloc[0]

Name    Alice
Age        23
City       aa
Name: 0, dtype: object

In [45]:
df.iloc[0:2]

    Name  Age City
0  Alice   23   aa
1    Bob   23   bb

smaplin and preview data using df.sample()

In [4]:
data={
    'Name':['Alice', 'Bob','ccc','dddd'],
    'Age':[23,23,45,55],
    'City': ['aa','bb',None,'cc']

}
df=pd.DataFrame(data)

NameError: name 'pd' is not defined

In [6]:
import pandas as pd

In [8]:
data={
    'Name':['Alice', 'Bob','ccc','dddd'],
    'Age':[23,None,45,55],
    'City': ['aa','bb',None,'cc']

}
df=pd.DataFrame(data)

In [9]:
data={
    'Name':['Alice', 'Bob','ccc','dddd'],
    'Age':[23,None,45,55],
    'City': ['aa','bb',None,'cc']

}
df=pd.DataFrame(data)

In [10]:
df

    Name   Age City
0  Alice  23.0   aa
1    Bob   NaN   bb
2    ccc  45.0  NaN
3   dddd  55.0   cc

In [11]:
df.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [12]:
df_clean=df.dropna()
df_clean

    Name   Age City
0  Alice  23.0   aa
3   dddd  55.0   cc

In [13]:
df_clean=df.dropna(axis=1)

In [14]:
df_clean

    Name
0  Alice
1    Bob
2    ccc
3   dddd

In [15]:
df['Age']=df['Age'].fillna(30)

In [16]:
df

    Name   Age City
0  Alice  23.0   aa
1    Bob  30.0   bb
2    ccc  45.0  NaN
3   dddd  55.0   cc

In [17]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [18]:
df

    Name   Age City
0  Alice  23.0   aa
1    Bob  30.0   bb
2    ccc  45.0  NaN
3   dddd  55.0   cc

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      float64
 2   City    3 non-null      str
dtypes: float64(1), str(2)
memory usage: 228.0 bytes

In [20]:
gp=df.groupby('Name')['Age'].sum()

In [21]:
gp

Name
Alice    23.0
Bob      30.0
ccc      45.0
dddd     55.0
Name: Age, dtype: float64

In [22]:
gp=df.groupby('Name')['Age'].agg(['sum','count','mean'])
gp

        sum  count  mean
Name
Alice  23.0      1  23.0
Bob    30.0      1  30.0
ccc    45.0      1  45.0
dddd   55.0      1  55.0