In [1]:
import pandas as pd

In [8]:
import sqlite3
conn=sqlite3.connect('chat_data.db')

In [7]:
df=pd.read_excel('data.xlsx')

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
0,ORD0001,2026-05-06,Priya Joshi,Kolkata,West Bengal,Mouse,Electronics,1,965.22,965.22,Credit Card,Riya Desai,1.0,Cancelled
1,ORD0002,2026-02-17,Priya Joshi,Vadodara,Gujarat,Backpack,Accessories,7,1547.16,10830.12,Credit Card,Karan Singh,5.0,Completed
2,ORD0003,2026-05-23,Aarav Patel,Hyderabad,Telangana,Monitor,Electronics,7,10993.59,76955.13,Credit Card,Riya Desai,4.0,Completed
3,ORD0004,2026-06-22,Riya Shah,Pune,Maharashtra,Keyboard,Electronics,4,2046.90,8187.60,UPI,Neha Joshi,1.0,Completed
4,ORD0005,2026-08-24,Karan Mehta,Delhi,Delhi,Backpack,Accessories,5,1965.85,9829.25,UPI,Neha Joshi,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,ORD0498,2026-02-28,Ananya Shah,Kolkata,West Bengal,Monitor,Electronics,7,13120.22,91841.54,Cash,Neha Joshi,2.0,Cancelled
498,ORD0499,2026-01-23,Rahul Mehta,Surat,Gujarat,Water Bottle,Accessories,7,599.71,4197.97,Net Banking,Karan Singh,2.0,Completed
499,ORD0500,2026-03-17,Aarav Patel,Kolkata,West Bengal,Pen Set,Stationery,1,279.31,279.31,Credit Card,Rahul Mehta,2.0,Cancelled
500,ORD0024,2026-01-28,Riya Shah,Delhi,Delhi,Desk,Furniture,7,6930.75,48515.25,UPI,Neha Joshi,4.0,Completed
501,ORD0099,2026-06-09,Karan Mehta,Ahmedabad,Gujarat,Water Bottle,Accessories,4,744.05,2976.20,UPI,Karan Singh,4.0,Completed

In [10]:
df.to_sql('chat_data.db',conn, if_exists='replace', index=False)
conn.close()

In [ ]:
### exporting data into yaml

In [11]:
import yaml

In [14]:
data_dict=df.to_dict(orient='records')

In [15]:
data_dict

[{'Order_ID': 'ORD0001',
  'Date': Timestamp('2026-05-06 00:00:00'),
  'Customer_Name': 'Priya Joshi',
  'City': 'Kolkata',
  'State': 'West Bengal',
  'Product': 'Mouse',
  'Category': 'Electronics',
  'Quantity': 1,
  'Unit_Price': 965.22,
  'Total_Sales': 965.22,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Riya Desai',
  'Rating': 1.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0002',
  'Date': Timestamp('2026-02-17 00:00:00'),
  'Customer_Name': 'Priya Joshi',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Backpack',
  'Category': 'Accessories',
  'Quantity': 7,
  'Unit_Price': 1547.16,
  'Total_Sales': 10830.12,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Karan Singh',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0003',
  'Date': Timestamp('2026-05-23 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Hyderabad',
  'State': 'Telangana',
  'Product': 'Monitor',
  'Category': 'Electronics',
  'Quantity': 7,
  'Unit_Price': 10993.59,
  'Total_Sales': 76955.13,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Riya Desai',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0004',
  'Date': Timestamp('2026-06-22 00:00:00'),
  'Customer_Name': 'Riya Shah',
  'City': 'Pune',
  'State': 'Maharashtra',
  'Product': 'Keyboard',
  'Category': 'Electronics',
  'Quantity': 4,
  'Unit_Price': 2046.9,
  'Total_Sales': 8187.6,
  'Payment_Method': 'UPI',
  'Salesperson': 'Neha Joshi',
  'Rating': 1.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0005',
  'Date': Timestamp('2026-08-24 00:00:00'),
  'Customer_Name': 'Karan Mehta',
  'City': 'Delhi',
  'State': 'Delhi',
  'Product': 'Backpack',
  'Category': 'Accessories',
  'Quantity': 5,
  'Unit_Price': 1965.85,
  'Total_Sales': 9829.25,
  'Payment_Method': 'UPI',
  'Salesperson': 'Neha Joshi',
  'Rating': 1.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0006',
  'Date': Timestamp('2026-02-05 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Pune',
  'State': 'Maharashtra',
  'Product': 'Water Bottle',
  'Category': 'Accessories',
  'Quantity': 6,
  'Unit_Price': 716.24,
  'Total_Sales': 4297.44,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Rahul Mehta',
  'Rating': 1.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0007',
  'Date': Timestamp('2026-07-06 00:00:00'),
  'Customer_Name': 'Rahul Mehta',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Desk',
  'Category': 'Furniture',
  'Quantity': 5,
  'Unit_Price': 6902.16,
  'Total_Sales': 34510.8,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Rahul Mehta',
  'Rating': 2.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0008',
  'Date': Timestamp('2026-03-29 00:00:00'),
  'Customer_Name': 'Karan Mehta',
  'City': 'Indore',
  'State': 'Madhya Pradesh',
  'Product': 'Water Bottle',
  'Category': 'Accessories',
  'Quantity': 2,
  'Unit_Price': 722.92,
  'Total_Sales': 1445.84,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Priya Patel',
  'Rating': 4.0,
  'Status': 'Pending'},
 {'Order_ID': 'ORD0009',
  'Date': Timestamp('2026-01-29 00:00:00'),
  'Customer_Name': 'Priya Joshi',
  'City': 'Pune',
  'State': 'Maharashtra',
  'Product': 'Water Bottle',
  'Category': 'Accessories',
  'Quantity': 4,
  'Unit_Price': 738.77,
  'Total_Sales': 2955.08,
  'Payment_Method': 'UPI',
  'Salesperson': 'Rahul Mehta',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0010',
  'Date': Timestamp('2026-09-13 00:00:00'),
  'Customer_Name': 'Arjun Patel',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Monitor',
  'Category': 'Electronics',
  'Quantity': 6,
  'Unit_Price': 10965.46,
  'Total_Sales': 65792.76,
  'Payment_Method': 'Cash',
  'Salesperson': 'Priya Patel',
  'Rating': 3.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0011',
  'Date': Timestamp('2026-08-08 00:00:00'),
  'Customer_Name': 'Sneha Joshi',
  'City': 'Mumbai',
  'State': 'Maharashtra',
  'Product': 'Smartphone',
  'Category': 'Electronics',
  'Quantity': 5,
  'Unit_Price': 30074.92,
  'Total_Sales': 150374.6,
  'Payment_Method': 'Cash',
  'Salesperson': 'Rahul Mehta',
  'Rating': 2.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0012',
  'Date': Timestamp('2026-02-26 00:00:00'),
  'Customer_Name': 'Rahul Mehta',
  'City': 'Hyderabad',
  'State': 'Telangana',
  'Product': 'Notebook',
  'Category': 'Stationery',
  'Quantity': 2,
  'Unit_Price': 129.21,
  'Total_Sales': 258.42,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Riya Desai',
  'Rating': 4.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0013',
  'Date': Timestamp('2026-08-28 00:00:00'),
  'Customer_Name': 'Karan Mehta',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Desk',
  'Category': 'Furniture',
  'Quantity': 7,
  'Unit_Price': 7201.37,
  'Total_Sales': 50409.59,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Karan Singh',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0014',
  'Date': Timestamp('2026-05-17 00:00:00'),
  'Customer_Name': nan,
  'City': 'Kolkata',
  'State': 'West Bengal',
  'Product': 'Smartphone',
  'Category': 'Electronics',
  'Quantity': 2,
  'Unit_Price': 29526.37,
  'Total_Sales': 59052.74,
  'Payment_Method': 'UPI',
  'Salesperson': 'Rahul Mehta',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0015',
  'Date': Timestamp('2026-04-02 00:00:00'),
  'Customer_Name': 'Karan Mehta',
  'City': 'Bengaluru',
  'State': 'Karnataka',
  'Product': 'Laptop',
  'Category': 'Electronics',
  'Quantity': 5,
  'Unit_Price': 62786.15,
  'Total_Sales': 313930.75,
  'Payment_Method': 'UPI',
  'Salesperson': 'Riya Desai',
  'Rating': 3.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0016',
  'Date': Timestamp('2026-03-24 00:00:00'),
  'Customer_Name': 'Karan Mehta',
  'City': 'Chennai',
  'State': 'Tamil Nadu',
  'Product': 'Monitor',
  'Category': 'Electronics',
  'Quantity': 3,
  'Unit_Price': 11546.09,
  'Total_Sales': 34638.27,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Amit Shah',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0017',
  'Date': Timestamp('2026-06-07 00:00:00'),
  'Customer_Name': 'Priya Joshi',
  'City': 'Bengaluru',
  'State': 'Karnataka',
  'Product': 'Laptop',
  'Category': 'Electronics',
  'Quantity': 2,
  'Unit_Price': 62080.13,
  'Total_Sales': 124160.26,
  'Payment_Method': 'UPI',
  'Salesperson': 'Priya Patel',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0018',
  'Date': Timestamp('2026-09-30 00:00:00'),
  'Customer_Name': 'Rahul Mehta',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Smartphone',
  'Category': 'Electronics',
  'Quantity': 8,
  'Unit_Price': 30654.6,
  'Total_Sales': 245236.8,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Riya Desai',
  'Rating': 4.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0019',
  'Date': Timestamp('2026-04-13 00:00:00'),
  'Customer_Name': 'Vikram Desai',
  'City': 'Surat',
  'State': 'Gujarat',
  'Product': 'Headphones',
  'Category': 'Electronics',
  'Quantity': 7,
  'Unit_Price': 2848.27,
  'Total_Sales': 19937.89,
  'Payment_Method': 'Cash',
  'Salesperson': 'Riya Desai',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0020',
  'Date': Timestamp('2026-04-26 00:00:00'),
  'Customer_Name': 'Riya Shah',
  'City': 'Bengaluru',
  'State': 'Karnataka',
  'Product': 'Pen Set',
  'Category': 'Stationery',
  'Quantity': 8,
  'Unit_Price': 221.58,
  'Total_Sales': 1772.64,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Amit Shah',
  'Rating': 5.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0021',
  'Date': Timestamp('2026-01-31 00:00:00'),
  'Customer_Name': 'Priya Joshi',
  'City': 'Mumbai',
  'State': 'Maharashtra',
  'Product': 'Backpack',
  'Category': 'Accessories',
  'Quantity': 4,
  'Unit_Price': 1533.88,
  'Total_Sales': 6135.52,
  'Payment_Method': 'UPI',
  'Salesperson': 'Amit Shah',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0022',
  'Date': Timestamp('2026-09-06 00:00:00'),
  'Customer_Name': 'Priya Joshi',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Pen Set',
  'Category': 'Stationery',
  'Quantity': 4,
  'Unit_Price': 233.39,
  'Total_Sales': 933.56,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Priya Patel',
  'Rating': 4.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0023',
  'Date': Timestamp('2026-07-28 00:00:00'),
  'Customer_Name': 'Priya Joshi',
  'City': 'Chennai',
  'State': 'Tamil Nadu',
  'Product': 'Notebook',
  'Category': 'Stationery',
  'Quantity': 4,
  'Unit_Price': 130.25,
  'Total_Sales': 521.0,
  'Payment_Method': 'UPI',
  'Salesperson': 'Amit Shah',
  'Rating': 4.0,
  'Status': 'Pending'},
 {'Order_ID': 'ORD0024',
  'Date': Timestamp('2026-01-28 00:00:00'),
  'Customer_Name': 'Riya Shah',
  'City': 'Delhi',
  'State': 'Delhi',
  'Product': 'Desk',
  'Category': 'Furniture',
  'Quantity': 7,
  'Unit_Price': 6930.75,
  'Total_Sales': 48515.25,
  'Payment_Method': 'UPI',
  'Salesperson': 'Neha Joshi',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0025',
  'Date': Timestamp('2026-08-18 00:00:00'),
  'Customer_Name': 'Rahul Mehta',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Monitor',
  'Category': 'Electronics',
  'Quantity': 4,
  'Unit_Price': 10884.75,
  'Total_Sales': 43539.0,
  'Payment_Method': 'Cash',
  'Salesperson': 'Priya Patel',
  'Rating': 3.0,
  'Status': 'Pending'},
 {'Order_ID': 'ORD0026',
  'Date': Timestamp('2026-02-20 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Mumbai',
  'State': 'Maharashtra',
  'Product': 'Mouse',
  'Category': 'Electronics',
  'Quantity': 8,
  'Unit_Price': 983.17,
  'Total_Sales': 7865.36,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Amit Shah',
  'Rating': 1.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0027',
  'Date': Timestamp('2026-07-25 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Surat',
  'State': 'Gujarat',
  'Product': 'Desk',
  'Category': 'Furniture',
  'Quantity': 8,
  'Unit_Price': 6960.85,
  'Total_Sales': 55686.8,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Neha Joshi',
  'Rating': 1.0,
  'Status': 'Pending'},
 {'Order_ID': 'ORD0028',
  'Date': Timestamp('2026-09-07 00:00:00'),
  'Customer_Name': 'Rahul Mehta',
  'City': 'Pune',
  'State': 'Maharashtra',
  'Product': 'Notebook',
  'Category': 'Stationery',
  'Quantity': 5,
  'Unit_Price': 117.23,
  'Total_Sales': 586.15,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Rahul Mehta',
  'Rating': 2.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0029',
  'Date': Timestamp('2026-01-30 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Chennai',
  'State': 'Tamil Nadu',
  'Product': 'Smartphone',
  'Category': 'Electronics',
  'Quantity': 1,
  'Unit_Price': 30082.99,
  'Total_Sales': 30082.99,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Neha Joshi',
  'Rating': 5.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0030',
  'Date': Timestamp('2026-02-05 00:00:00'),
  'Customer_Name': 'Sneha Joshi',
  'City': 'Surat',
  'State': 'Gujarat',
  'Product': 'Laptop',
  'Category': 'Electronics',
  'Quantity': 2,
  'Unit_Price': 60797.15,
  'Total_Sales': 121594.3,
  'Payment_Method': 'UPI',
  'Salesperson': 'Riya Desai',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0031',
  'Date': Timestamp('2026-01-21 00:00:00'),
  'Customer_Name': 'Sneha Joshi',
  'City': 'Jaipur',
  'State': 'Rajasthan',
  'Product': 'Mouse',
  'Category': 'Electronics',
  'Quantity': 4,
  'Unit_Price': 921.31,
  'Total_Sales': 3685.24,
  'Payment_Method': 'UPI',
  'Salesperson': 'Neha Joshi',
  'Rating': 4.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0032',
  'Date': Timestamp('2026-04-15 00:00:00'),
  'Customer_Name': 'Neha Singh',
  'City': 'Chennai',
  'State': 'Tamil Nadu',
  'Product': 'Pen Set',
  'Category': 'Stationery',
  'Quantity': 6,
  'Unit_Price': 282.6,
  'Total_Sales': 1695.6,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Rahul Mehta',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0033',
  'Date': Timestamp('2026-02-07 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Kolkata',
  'State': 'West Bengal',
  'Product': 'Water Bottle',
  'Category': 'Accessories',
  'Quantity': 5,
  'Unit_Price': 691.02,
  'Total_Sales': 3455.1,
  'Payment_Method': 'Cash',
  'Salesperson': 'Karan Singh',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0034',
  'Date': Timestamp('2026-03-09 00:00:00'),
  'Customer_Name': 'Neha Singh',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Pen Set',
  'Category': 'Stationery',
  'Quantity': 4,
  'Unit_Price': 250.44,
  'Total_Sales': 1001.76,
  'Payment_Method': 'UPI',
  'Salesperson': 'Priya Patel',
  'Rating': 3.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0035',
  'Date': Timestamp('2026-09-28 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Surat',
  'State': 'Gujarat',
  'Product': 'Notebook',
  'Category': 'Stationery',
  'Quantity': 5,
  'Unit_Price': 124.02,
  'Total_Sales': 620.1,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Rahul Mehta',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0036',
  'Date': Timestamp('2026-03-21 00:00:00'),
  'Customer_Name': 'Vikram Desai',
  'City': 'Surat',
  'State': 'Gujarat',
  'Product': 'Headphones',
  'Category': 'Electronics',
  'Quantity': 2,
  'Unit_Price': 2792.28,
  'Total_Sales': 5584.56,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Karan Singh',
  'Rating': 2.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0037',
  'Date': Timestamp('2026-05-09 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Mumbai',
  'State': 'Maharashtra',
  'Product': 'Water Bottle',
  'Category': 'Accessories',
  'Quantity': 5,
  'Unit_Price': 701.14,
  'Total_Sales': 3505.7,
  'Payment_Method': 'UPI',
  'Salesperson': 'Riya Desai',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0038',
  'Date': Timestamp('2026-05-15 00:00:00'),
  'Customer_Name': 'Rahul Mehta',
  'City': 'Ahmedabad',
  'State': 'Gujarat',
  'Product': 'Laptop',
  'Category': 'Electronics',
  'Quantity': 6,
  'Unit_Price': 59473.47,
  'Total_Sales': 356840.82,
  'Payment_Method': 'Cash',
  'Salesperson': 'Karan Singh',
  'Rating': 4.0,
  'Status': 'Pending'},
 {'Order_ID': 'ORD0039',
  'Date': Timestamp('2026-03-18 00:00:00'),
  'Customer_Name': 'Karan Mehta',
  'City': 'Hyderabad',
  'State': 'Telangana',
  'Product': 'Laptop',
  'Category': 'Electronics',
  'Quantity': 2,
  'Unit_Price': 47991.52,
  'Total_Sales': 95983.04,
  'Payment_Method': 'UPI',
  'Salesperson': 'Rahul Mehta',
  'Rating': 5.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0040',
  'Date': Timestamp('2026-07-06 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Surat',
  'State': 'Gujarat',
  'Product': 'Desk',
  'Category': 'Furniture',
  'Quantity': 3,
  'Unit_Price': 6037.84,
  'Total_Sales': 18113.52,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Priya Patel',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0041',
  'Date': Timestamp('2026-07-28 00:00:00'),
  'Customer_Name': 'Sneha Joshi',
  'City': 'Kolkata',
  'State': 'West Bengal',
  'Product': 'Mouse',
  'Category': 'Electronics',
  'Quantity': 6,
  'Unit_Price': 975.63,
  'Total_Sales': 5853.78,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Priya Patel',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0042',
  'Date': Timestamp('2026-06-20 00:00:00'),
  'Customer_Name': 'Arjun Patel',
  'City': 'Surat',
  'State': 'Gujarat',
  'Product': 'Desk',
  'Category': 'Furniture',
  'Quantity': 1,
  'Unit_Price': 6326.66,
  'Total_Sales': 6326.66,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Rahul Mehta',
  'Rating': 2.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0043',
  'Date': Timestamp('2026-08-24 00:00:00'),
  'Customer_Name': 'Neha Singh',
  'City': 'Jaipur',
  'State': 'Rajasthan',
  'Product': 'Laptop',
  'Category': 'Electronics',
  'Quantity': 8,
  'Unit_Price': 50420.16,
  'Total_Sales': 403361.28,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Priya Patel',
  'Rating': 2.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0044',
  'Date': Timestamp('2026-02-05 00:00:00'),
  'Customer_Name': 'Vikram Desai',
  'City': 'Kolkata',
  'State': 'West Bengal',
  'Product': 'Monitor',
  'Category': 'Electronics',
  'Quantity': 7,
  'Unit_Price': 11381.74,
  'Total_Sales': 79672.18,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Riya Desai',
  'Rating': 5.0,
  'Status': 'Pending'},
 {'Order_ID': 'ORD0045',
  'Date': Timestamp('2026-03-01 00:00:00'),
  'Customer_Name': 'Vikram Desai',
  'City': 'Kolkata',
  'State': 'West Bengal',
  'Product': 'Pen Set',
  'Category': 'Stationery',
  'Quantity': 6,
  'Unit_Price': 282.94,
  'Total_Sales': 1697.64,
  'Payment_Method': 'Credit Card',
  'Salesperson': 'Karan Singh',
  'Rating': 3.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0046',
  'Date': Timestamp('2026-06-10 00:00:00'),
  'Customer_Name': 'Arjun Patel',
  'City': 'Vadodara',
  'State': 'Gujarat',
  'Product': 'Backpack',
  'Category': 'Accessories',
  'Quantity': 7,
  'Unit_Price': 1716.67,
  'Total_Sales': 12016.69,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Karan Singh',
  'Rating': 1.0,
  'Status': 'Pending'},
 {'Order_ID': 'ORD0047',
  'Date': Timestamp('2026-08-12 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Chennai',
  'State': 'Tamil Nadu',
  'Product': 'Monitor',
  'Category': 'Electronics',
  'Quantity': 5,
  'Unit_Price': 10359.79,
  'Total_Sales': 51798.95,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Karan Singh',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0048',
  'Date': Timestamp('2026-06-19 00:00:00'),
  'Customer_Name': 'Sneha Joshi',
  'City': 'Delhi',
  'State': 'Delhi',
  'Product': 'Desk',
  'Category': 'Furniture',
  'Quantity': 2,
  'Unit_Price': 7942.64,
  'Total_Sales': 15885.28,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Riya Desai',
  'Rating': 5.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0049',
  'Date': Timestamp('2026-06-17 00:00:00'),
  'Customer_Name': 'Arjun Patel',
  'City': 'Indore',
  'State': 'Madhya Pradesh',
  'Product': 'Headphones',
  'Category': 'Electronics',
  'Quantity': 5,
  'Unit_Price': 2625.17,
  'Total_Sales': 13125.85,
  'Payment_Method': 'Debit Card',
  'Salesperson': 'Karan Singh',
  'Rating': 2.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0050',
  'Date': Timestamp('2026-03-31 00:00:00'),
  'Customer_Name': 'Sneha Joshi',
  'City': 'Jaipur',
  'State': 'Rajasthan',
  'Product': 'Water Bottle',
  'Category': 'Accessories',
  'Quantity': 7,
  'Unit_Price': 737.24,
  'Total_Sales': 5160.68,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Rahul Mehta',
  'Rating': 4.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0051',
  'Date': Timestamp('2026-06-14 00:00:00'),
  'Customer_Name': 'Ananya Shah',
  'City': 'Ahmedabad',
  'State': 'Gujarat',
  'Product': 'Headphones',
  'Category': 'Electronics',
  'Quantity': 5,
  'Unit_Price': 2282.64,
  'Total_Sales': 11413.2,
  'Payment_Method': 'Cash',
  'Salesperson': 'Neha Joshi',
  'Rating': 4.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0052',
  'Date': Timestamp('2026-05-26 00:00:00'),
  'Customer_Name': 'Karan Mehta',
  'City': 'Hyderabad',
  'State': 'Telangana',
  'Product': 'Notebook',
  'Category': 'Stationery',
  'Quantity': 3,
  'Unit_Price': 125.72,
  'Total_Sales': 377.16,
  'Payment_Method': 'Net Banking',
  'Salesperson': 'Rahul Mehta',
  'Rating': 1.0,
  'Status': 'Completed'},
 {'Order_ID': 'ORD0053',
  'Date': Timestamp('2026-03-17 00:00:00'),
  'Customer_Name': 'Aarav Patel',
  'City': 'Kolkata',
  'State': 'West Bengal',
  'Product': 'Headphones',
  'Category': 'Electronics',
  'Quantity': 4,
  'Unit_Price': 2729.92,
  'Total_Sales': 10919.68,
  'Payment_Method': 'UPI',
  'Salesperson': 'Priya Patel',
  'Rating': 4.0,
  'Status': 'Cancelled'},
 {'Order_ID': 'ORD0054',
  'Date': Timestamp('2026-04-10 00:00:00'),
  'Customer_Name': 'Arjun Patel',
  'City': 'Vadodara',
  'State': 'Gujarat',

In [ ]:
with open('chat_data.yaml','w') as file:
    yaml.damp(data_dict,file)

In [18]:
df

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
0,ORD0001,2026-05-06,Priya Joshi,Kolkata,West Bengal,Mouse,Electronics,1,965.22,965.22,Credit Card,Riya Desai,1.0,Cancelled
1,ORD0002,2026-02-17,Priya Joshi,Vadodara,Gujarat,Backpack,Accessories,7,1547.16,10830.12,Credit Card,Karan Singh,5.0,Completed
2,ORD0003,2026-05-23,Aarav Patel,Hyderabad,Telangana,Monitor,Electronics,7,10993.59,76955.13,Credit Card,Riya Desai,4.0,Completed
3,ORD0004,2026-06-22,Riya Shah,Pune,Maharashtra,Keyboard,Electronics,4,2046.90,8187.60,UPI,Neha Joshi,1.0,Completed
4,ORD0005,2026-08-24,Karan Mehta,Delhi,Delhi,Backpack,Accessories,5,1965.85,9829.25,UPI,Neha Joshi,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,ORD0498,2026-02-28,Ananya Shah,Kolkata,West Bengal,Monitor,Electronics,7,13120.22,91841.54,Cash,Neha Joshi,2.0,Cancelled
498,ORD0499,2026-01-23,Rahul Mehta,Surat,Gujarat,Water Bottle,Accessories,7,599.71,4197.97,Net Banking,Karan Singh,2.0,Completed
499,ORD0500,2026-03-17,Aarav Patel,Kolkata,West Bengal,Pen Set,Stationery,1,279.31,279.31,Credit Card,Rahul Mehta,2.0,Cancelled
500,ORD0024,2026-01-28,Riya Shah,Delhi,Delhi,Desk,Furniture,7,6930.75,48515.25,UPI,Neha Joshi,4.0,Completed
501,ORD0099,2026-06-09,Karan Mehta,Ahmedabad,Gujarat,Water Bottle,Accessories,4,744.05,2976.20,UPI,Karan Singh,4.0,Completed

In [19]:
df.head(3)

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
0,ORD0001,2026-05-06,Priya Joshi,Kolkata,West Bengal,Mouse,Electronics,1,965.22,965.22,Credit Card,Riya Desai,1.0,Cancelled
1,ORD0002,2026-02-17,Priya Joshi,Vadodara,Gujarat,Backpack,Accessories,7,1547.16,10830.12,Credit Card,Karan Singh,5.0,Completed
2,ORD0003,2026-05-23,Aarav Patel,Hyderabad,Telangana,Monitor,Electronics,7,10993.59,76955.13,Credit Card,Riya Desai,4.0,Completed

In [21]:
random_row=df.sample(n=3)
random_row

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
334,ORD0335,2026-07-23,Karan Mehta,Mumbai,Maharashtra,Laptop,Electronics,1,62403.22,62403.22,Debit Card,Riya Desai,4.0,Cancelled
138,ORD0139,2026-02-13,Riya Shah,Surat,Gujarat,Water Bottle,Accessories,8,609.10,4872.80,Cash,Amit Shah,4.0,Completed
229,ORD0230,2026-05-03,Priya Joshi,Pune,Maharashtra,Pen Set,Stationery,5,222.80,1114.00,UPI,Riya Desai,5.0,Completed

In [27]:
random_sample=df.sample(frac=0.3)
random_sample

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
29,ORD0030,2026-02-05,Sneha Joshi,Surat,Gujarat,Laptop,Electronics,2,60797.15,121594.30,UPI,Riya Desai,5.0,Completed
60,ORD0061,2026-08-04,Arjun Patel,Hyderabad,Telangana,Notebook,Stationery,7,104.24,729.68,Net Banking,Riya Desai,1.0,Cancelled
77,ORD0078,2026-05-05,Vikram Desai,Vadodara,Gujarat,Headphones,Electronics,4,2428.30,9713.20,Net Banking,Rahul Mehta,4.0,Cancelled
324,ORD0325,2026-04-26,Karan Mehta,Ahmedabad,Gujarat,Monitor,Electronics,8,10480.58,83844.64,Cash,Amit Shah,1.0,Completed
44,ORD0045,2026-03-01,Vikram Desai,Kolkata,West Bengal,Pen Set,Stationery,6,282.94,1697.64,Credit Card,Karan Singh,3.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,ORD0101,2026-03-16,Arjun Patel,Jaipur,Rajasthan,Notebook,Stationery,8,110.77,886.16,Credit Card,Karan Singh,5.0,Completed
118,ORD0119,2026-07-07,Karan Mehta,Surat,Gujarat,Monitor,Electronics,3,13031.45,39094.35,Net Banking,Rahul Mehta,NaN,Completed
337,ORD0338,2026-03-01,Ananya Shah,Ahmedabad,Gujarat,Monitor,Electronics,2,13528.66,27057.32,Net Banking,Karan Singh,1.0,Completed
163,ORD0164,2026-07-17,Vikram Desai,Vadodara,Gujarat,Office Chair,Furniture,2,8647.81,17295.62,Debit Card,Riya Desai,5.0,Cancelled
420,ORD0421,2026-06-26,Vikram Desai,Kolkata,West Bengal,Smartphone,Electronics,4,25700.63,102802.52,Credit Card,Amit Shah,4.0,Cancelled

In [28]:
### filter

In [29]:
mask=df['Quantity']>3
mask

0      False
1       True
2       True
3       True
4       True
       ...
497     True
498     True
499    False
500     True
501     True
Name: Quantity, Length: 502, dtype: bool

In [30]:
filtered_df=df[mask]

In [31]:
filtered_df

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
1,ORD0002,2026-02-17,Priya Joshi,Vadodara,Gujarat,Backpack,Accessories,7,1547.16,10830.12,Credit Card,Karan Singh,5.0,Completed
2,ORD0003,2026-05-23,Aarav Patel,Hyderabad,Telangana,Monitor,Electronics,7,10993.59,76955.13,Credit Card,Riya Desai,4.0,Completed
3,ORD0004,2026-06-22,Riya Shah,Pune,Maharashtra,Keyboard,Electronics,4,2046.90,8187.60,UPI,Neha Joshi,1.0,Completed
4,ORD0005,2026-08-24,Karan Mehta,Delhi,Delhi,Backpack,Accessories,5,1965.85,9829.25,UPI,Neha Joshi,1.0,Cancelled
5,ORD0006,2026-02-05,Aarav Patel,Pune,Maharashtra,Water Bottle,Accessories,6,716.24,4297.44,Credit Card,Rahul Mehta,1.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,ORD0497,2026-03-22,Neha Singh,Kolkata,West Bengal,Headphones,Electronics,4,2237.68,8950.72,Net Banking,Riya Desai,5.0,Completed
497,ORD0498,2026-02-28,Ananya Shah,Kolkata,West Bengal,Monitor,Electronics,7,13120.22,91841.54,Cash,Neha Joshi,2.0,Cancelled
498,ORD0499,2026-01-23,Rahul Mehta,Surat,Gujarat,Water Bottle,Accessories,7,599.71,4197.97,Net Banking,Karan Singh,2.0,Completed
500,ORD0024,2026-01-28,Riya Shah,Delhi,Delhi,Desk,Furniture,7,6930.75,48515.25,UPI,Neha Joshi,4.0,Completed
501,ORD0099,2026-06-09,Karan Mehta,Ahmedabad,Gujarat,Water Bottle,Accessories,4,744.05,2976.20,UPI,Karan Singh,4.0,Completed

In [34]:
mask=df['Quantity']>3 & (df['Unit_Price']>100 )
mask

0      False
1       True
2       True
3       True
4       True
       ...
497     True
498     True
499    False
500     True
501     True
Length: 502, dtype: bool

In [35]:
df

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
0,ORD0001,2026-05-06,Priya Joshi,Kolkata,West Bengal,Mouse,Electronics,1,965.22,965.22,Credit Card,Riya Desai,1.0,Cancelled
1,ORD0002,2026-02-17,Priya Joshi,Vadodara,Gujarat,Backpack,Accessories,7,1547.16,10830.12,Credit Card,Karan Singh,5.0,Completed
2,ORD0003,2026-05-23,Aarav Patel,Hyderabad,Telangana,Monitor,Electronics,7,10993.59,76955.13,Credit Card,Riya Desai,4.0,Completed
3,ORD0004,2026-06-22,Riya Shah,Pune,Maharashtra,Keyboard,Electronics,4,2046.90,8187.60,UPI,Neha Joshi,1.0,Completed
4,ORD0005,2026-08-24,Karan Mehta,Delhi,Delhi,Backpack,Accessories,5,1965.85,9829.25,UPI,Neha Joshi,1.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,ORD0498,2026-02-28,Ananya Shah,Kolkata,West Bengal,Monitor,Electronics,7,13120.22,91841.54,Cash,Neha Joshi,2.0,Cancelled
498,ORD0499,2026-01-23,Rahul Mehta,Surat,Gujarat,Water Bottle,Accessories,7,599.71,4197.97,Net Banking,Karan Singh,2.0,Completed
499,ORD0500,2026-03-17,Aarav Patel,Kolkata,West Bengal,Pen Set,Stationery,1,279.31,279.31,Credit Card,Rahul Mehta,2.0,Cancelled
500,ORD0024,2026-01-28,Riya Shah,Delhi,Delhi,Desk,Furniture,7,6930.75,48515.25,UPI,Neha Joshi,4.0,Completed
501,ORD0099,2026-06-09,Karan Mehta,Ahmedabad,Gujarat,Water Bottle,Accessories,4,744.05,2976.20,UPI,Karan Singh,4.0,Completed

In [36]:
fl=df[df['Quantity'].between(2,5)]

In [37]:
fl

,Order_ID,Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Total_Sales,Payment_Method,Salesperson,Rating,Status
3,ORD0004,2026-06-22,Riya Shah,Pune,Maharashtra,Keyboard,Electronics,4,2046.90,8187.60,UPI,Neha Joshi,1.0,Completed
4,ORD0005,2026-08-24,Karan Mehta,Delhi,Delhi,Backpack,Accessories,5,1965.85,9829.25,UPI,Neha Joshi,1.0,Cancelled
6,ORD0007,2026-07-06,Rahul Mehta,Vadodara,Gujarat,Desk,Furniture,5,6902.16,34510.80,Debit Card,Rahul Mehta,2.0,Completed
7,ORD0008,2026-03-29,Karan Mehta,Indore,Madhya Pradesh,Water Bottle,Accessories,2,722.92,1445.84,Credit Card,Priya Patel,4.0,Pending
8,ORD0009,2026-01-29,Priya Joshi,Pune,Maharashtra,Water Bottle,Accessories,4,738.77,2955.08,UPI,Rahul Mehta,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,ORD0491,2026-03-16,Ananya Shah,Surat,Gujarat,Notebook,Stationery,3,108.45,325.35,Debit Card,Amit Shah,2.0,Pending
491,ORD0492,2026-01-22,Priya Joshi,Mumbai,Maharashtra,Mouse,Electronics,5,864.75,4323.75,Net Banking,Rahul Mehta,4.0,Pending
493,ORD0494,2026-07-13,Neha Singh,Indore,Madhya Pradesh,Headphones,Electronics,3,2407.49,7222.47,Net Banking,Riya Desai,5.0,Completed
496,ORD0497,2026-03-22,Neha Singh,Kolkata,West Bengal,Headphones,Electronics,4,2237.68,8950.72,Net Banking,Riya Desai,5.0,Completed
501,ORD0099,2026-06-09,Karan Mehta,Ahmedabad,Gujarat,Water Bottle,Accessories,4,744.05,2976.20,UPI,Karan Singh,4.0,Completed